run:
  timeout: 10m
  modules-download-mode: vendor
  build-tags:
    - netgo
    - require_docker

output:
  format: line-number

linters:
  enable:
    - goimports
    - golint
    - misspell
    - gofmt
    - depguard

linters-settings:
  depguard:
    list-type: blacklist
    packages-with-error-message:
      - github.com/go-kit/kit/log: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
  errcheck:
    exclude: ./.errcheck-exclude
  goimports:
    local-prefixes: "github.com/grafana/cortextool"
